version: "3"

services:
  dbeaver:
    hostname: dbeaver
    container_name: dbeaver
    image: dbeaver/cloudbeaver:latest
    ports:
      - '8978:8978'
    volumes:
      - ./workspace:/opt/cloudbeaver/workspace

networks:
  default:
    external:
      name: poc