version: "3"

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - ./metabase-data:/metabase-data
    # - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
      # MB_DB_TYPE: postgres
      # MB_DB_DBNAME: metabaseappdb
      # MB_DB_PORT: 5432
      # MB_DB_USER: metabase
      # MB_DB_PASS: mysecretpassword
      # MB_DB_HOST: postgres-metabase
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    # depends_on: 
    #   - postgres-metabase

  # postgres-metabase:
  #   image: postgres:latest
  #   container_name: postgres-metabase
  #   hostname: postgres-metabase
  #   environment:
  #     POSTGRES_USER: metabase
  #     POSTGRES_DB: metabaseappdb
  #     POSTGRES_PASSWORD: mysecretpassword

networks:
  default:
    external:
      name: poc
