version: "3"

services:
  sftp:
    container_name: sftp
    image: atmoz/sftp:latest
    volumes:
      - ./upload:/home/foo/upload
    ports:
      - "2222:22"
    command: foo:pass:1001

networks:
  default:
    external:
      name: poc