version: "3"

services:
  minio:
    hostname: minio
    container_name: minio
    image: 'minio/minio:RELEASE.2024-01-13T07-53-03Z'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    command: server /data --console-address ":9001"

  createbucket:
    hostname: createbucket
    container_name: createbucket
    image: minio/mc:RELEASE.2024-01-13T08-44-48Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 accesskey secretkey;
      /usr/bin/mc mb myminio/datalake-landing;
      /usr/bin/mc anonymous set public myminio/datalake-landing;
      /usr/bin/mc mb myminio/datalake-bronze;
      /usr/bin/mc anonymous set public myminio/datalake-bronze;
      /usr/bin/mc mb myminio/datalake-silver;
      /usr/bin/mc anonymous set public myminio/datalake-silver;
      /usr/bin/mc mb myminio/datalake-gold;
      /usr/bin/mc anonymous set public myminio/datalake-gold;
      /usr/bin/mc mb myminio/datalake/warehouse;
      /usr/bin/mc anonymous set public myminio/datalake/warehouse;
      "

networks:
  default:
    external:
      name: poc
