version: "3"
services:

  zookeeper: # this is the config manager
    container_name: zookeeper
    user: root
    hostname: zookeeper
    image: "bitnami/zookeeper:latest"
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  nifi-registry:
    image: "apache/nifi-registry:latest"
    container_name: nifi-registry
    user: root
    ports:
      - 19090:19090
    volumes:
      - ./configs/nifi_registry_current/conf:/opt/nifi-registry/nifi-registry-current/conf
      - ./configs/nifi_registry_current/database:/opt/nifi-registry/nifi-registry-current/database
      - ./configs/nifi_registry_current/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
    # uncomment one line above after execute `make nifi-registry-config`
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=19090
    restart: on-failure

  nifi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nifi
    user: root
    depends_on:
      - zookeeper
      - nifi-registry
    volumes:
      - ./configs/database_repository:/opt/nifi/nifi-current/database_repository
      - ./configs/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./configs/content_repository:/opt/nifi/nifi-current/content_repository
      - ./configs/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./configs/state:/opt/nifi/nifi-current/state
      - ./configs/logs:/opt/nifi/nifi-current/logs
      - ./minio_sites:/opt/nifi/nifi-current/minio_sites
      # uncomment two lines below after execute `make nifi-config`
      - ./configs/conf:/opt/nifi/nifi-current/conf
      - ./configs/drivers:/opt/nifi/drivers
    ports:
      - 8443:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      # - NIFI_CLUSTER_IS_NODE=true
      # - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY='12345678901234567890A'
    restart: always

networks:
  default:
    external:
      name: poc
